026 nov 10 adding accordion controls
bluewave-labs/verifywise pull request #254
Opened 2024-11-17 21:13 UTC by melpsh

This PR introduces significant changes, but I’ve intentionally kept it smaller to make the review process more manageable and avoid overwhelming you. (but keep in mind more changes on the way ) Here's an overview of what has been implemented:

1- Added all the accordions based on the structure outlined in the Excel file.
2- Developed a new data structure tailored to the updated data format.
3- Created individual tables and control panes dynamically, based on the data generated by each accordion.
4- Updated sub-control titles to reflect the corresponding accordion, row, and number of sub-controls accurately.

2024-11-17 21:16 UTC, melpsh commented
![image](https://github.com/user-attachments/assets/341a3260-a5f5-4b90-9360-9a23dbc9587d)
![image](https://github.com/user-attachments/assets/c6c3f416-4059-41b3-9b91-baa08df3e04e)

2024-11-18 00:28 UTC, gorkem-bwl commented
If we can fix the corresponding area like this, we're good to go:

- Subcontrol 1.2 (Subcontrol number) - Inter semibold 16px
- Subcontrol text - Inter regular 13px

![image](https://github.com/user-attachments/assets/b2585fbb-69a4-4c99-a747-1f94bb5ec4c5)

2024-11-18 05:27 UTC, MuhammadKhalilzadeh commented on Clients/src/presentation/components/Modals/Controlpane/index.tsx
> +  subControlTlts: string[];
This is a detailed good suggestion.
Make sure you take care of this.

2024-11-18 05:29 UTC, MuhammadKhalilzadeh commented on Clients/src/presentation/components/Modals/Controlpane/index.tsx
>    };
Please consider this comment also.
If the functionality is different, change the naming.

2024-11-18 05:34 UTC, MuhammadKhalilzadeh commented on Clients/src/presentation/components/Modals/Controlpane/index.tsx
### Improvements and Advanced Practices

**TypeScript Best Practices**

- Ensure all props and states have explicit types.
- Use TypeScript's Record<string, any> or more specific types instead of any for title and content if possible.

**Readability and Maintainability**

- Break down the CustomModal component into smaller sub-components for specific functionalities.
- Add comments to explain complex pieces of logic.
- Use destructuring for state variables and props to enhance readability.

**Performance Optimization**

- Memoize functions and components to prevent unnecessary re-renders using useMemo and React.memo.

**Error Handling**

- Add proper error handling for API calls and user inputs.
- Use try-catch blocks to manage errors gracefully.

**Advanced React Practices**

- Use the Context API or Redux for managing global state if necessary.
- Implement code splitting using React.lazy and Suspense for better performance.

2024-11-18 05:36 UTC, MuhammadKhalilzadeh commented on Clients/src/presentation/pages/ComplianceTracker/index.tsx
> +    console.log("🚀 ~ renderAccordion ~ sectionDataaaaaaa:", sectionData)
🔃 Consider this one please

2024-11-18 05:43 UTC, MuhammadKhalilzadeh commented on Clients/src/presentation/mocks/compliance.data.ts
### Improving the ComplianceTracker Component

**TypeScript Best Practices**

- Explicitly define types for props and state variables.
- Use interfaces or types for complex objects instead of any.

**Readability and Maintainability**

- Break down large components into smaller, reusable components.
- Add JSDoc comments to explain functions and complex logic.
- Use destructuring for props and state variables for clarity

**Performance Optimization**

- Memoize functions and components using useMemo and React.memo to prevent unnecessary re-renders.

**Error Handling**

- Add proper error handling for API calls and user inputs.
- Use try-catch blocks to manage errors gracefully

**Advanced React Practices**

- Use the Context API or Redux for global state management if necessary.
- Implement code splitting using React.lazy and Suspense for better performance.
- Use hooks like `useCallback` and `useEffect` efficiently.

2024-11-18 05:43 UTC, MuhammadKhalilzadeh requested changes
@melpsh 
Thank you for the nice code.
Please apply the requested changes.

2024-11-21 05:41 UTC, merged